# Tensorflow 1

In [3]:
import tensorflow as tf

node1=tf.constant(4.0,tf.float32)
node2=tf.constant(3.0)
print(node1,node2)
node3=node1*node2

# launch the graph in session
sess=tf.Session()
print(sess.run([node1,node2]))
print(sess.run(node3))
print(sess.run(node3))

a=tf.placeholder(tf.float32) #placeholder
b=tf.placeholder(tf.float32) #placeholder
adder_node=a+b
print(sess.run(adder_node,{a:[1,3],b:[2,4]}))

W=tf.Variable([.3],tf.float32)
b=tf.Variable([-.3],tf.float32)
x=tf.placeholder(tf.float32)
linear_model=W*x+b
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(linear_model,{x:[1,2,3,4,5,6,7,8,9]}))

x=tf.add(5,3) # can use subtract, multiply as well
print(sess.run(x))

with tf.Session() as sess:
    print(sess.run(tf.cast(tf.constant(2.0),tf.int32)))


Tensor("Const_4:0", shape=(), dtype=float32) Tensor("Const_5:0", shape=(), dtype=float32)
[4.0, 3.0]
12.0
12.0
[3. 7.]
[0.         0.3        0.6        0.90000004 1.2        1.5
 1.8000002  2.1000001  2.4       ]
8
2


In [4]:
# 1/(1+exp(-x))
import numpy as np
def sigmoid_(a):
    return 1/(1+np.exp(-a))
a=[-4,-2,0,2,4]
for i in a:
    print(sigmoid_(i))


0.01798620996209156
0.11920292202211755
0.5
0.8807970779778823
0.9820137900379085


In [5]:
# tanh(a)=(e^a-e^-a)/e^a+e^-a
#import numpy as np
#def tanh_(a):
#    return (pow(2.75,a)-pow(2.75,-a))/pow(2.75,a)+pow(2.75,-a)
#for i in a:
#    print(tanh_(i))

def tanh_(a):
    return np.tanh(a)
print(tanh_(.3))
for i in a:
    print(tanh_(i))
    
    

0.2913126124515909
-0.999329299739067
-0.9640275800758169
0.0
0.9640275800758169
0.999329299739067


In [7]:
round(1.2334,2)

# softmax
Scores=[12,8,.3]
import numpy as np
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x), axis=0)
print(softmax(Scores))
print(sum(softmax(Scores)))

# Sigmoid
import numpy as np
a=[.2,1,0,3,-2]
sigmoid_Activation=tf.sigmoid(a)
tanh_Activation=tf.tanh(a)
relu_Activation=tf.nn.relu(a)
with tf.Session() as sess:
    output1=sess.run(sigmoid_Activation)
    output2=sess.run(tanh_Activation)
    output3=sess.run(relu_Activation)
    print("sigmoid_Activation : ",output1)
    print("tanh_Activation : ",output2)
    print("relu_Activation : ",output3)

sess.close()

[9.82005792e-01 1.79860635e-02 8.14457845e-06]
1.0
sigmoid_Activation :  [0.54983395 0.7310586  0.5        0.95257413 0.11920292]
tanh_Activation :  [ 0.19737528  0.7615942   0.          0.9950547  -0.9640276 ]
relu_Activation :  [0.2 1.  0.  3.  0. ]


In [8]:
# Optimizers modifies each variable according to the derivative of loss w.r.t to that variable.

# LOSS FUNCTION
W=tf.Variable([.5],tf.float32)
b=tf.Variable([.1],tf.float32)
x=tf.placeholder(tf.float32)
y=tf.placeholder(tf.float32)
linear_model=W*x+b
squared_delta=tf.square(linear_model-y)
loss=tf.reduce_sum(squared_delta)

optimizer=tf.train.GradientDescentOptimizer(0.01)
train=optimizer.minimize(loss)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
for i in range(3):
    sess.run(train,{x:[1,2,3,4],y:[0,-1,-2,-3]})
print(sess.run([W,b]))
#print(sess.run(loss))



Instructions for updating:
Use tf.cast instead.
[array([-0.54620796], dtype=float32), array([-0.20577921], dtype=float32)]


In [10]:
# Simplest TensorFlow Neuron
import tensorflow as tf
weight=tf.Variable(0.8)
input_value=tf.constant(1.0)
output_value=weight*input_value
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(output_value))



0.8


In [11]:
# AND GATE
T,F =1., -1.   # o doesn't give correct o/p for false hence we take -1  
bias=1
train_in=[
    [T,T,bias],
    [T,F,bias],
    [F,T,bias],
    [F,F,bias]
]
train_out=[
    [T],
    [F],
    [F],
    [F]
]

w=tf.Variable(tf.random_normal([3,1]))

# step(x)={1 IF X>0; -1 otherwise}
def step(x):
    is_greater=tf.greater(x,0)
    as_float=tf.to_float(is_greater)
    doubled=tf.multiply(as_float,2)
    return tf.subtract(doubled,1)

output = step(tf.matmul(train_in,w))
error=tf.subtract(train_out,output)
mse=tf.reduce_mean(tf.square(error))

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(output))
print(sess.run(error))
print(sess.run(mse))


Instructions for updating:
Use tf.cast instead.
[[ 1.]
 [-1.]
 [ 1.]
 [-1.]]
[[ 0.]
 [ 0.]
 [-2.]
 [ 0.]]
1.0


In [12]:
# OR GATE
T,F =1., -1.   # o doesn't give correct o/p for false hence we take -1  
bias=1
train_in=[
    [T,T,bias],
    [T,F,bias],
    [F,T,bias],
    [F,F,bias]
]
train_out=[
    [T],
    [T],
    [T],
    [F]
]

w=tf.Variable(tf.random_normal([3,1]))

# step(x)={1 IF X>0; -1 otherwise}
def step(x):
    is_greater=tf.greater(x,0)
    as_float=tf.to_float(is_greater)
    doubled=tf.multiply(as_float,2)
    return tf.subtract(doubled,1)

output = step(tf.matmul(train_in,w))
error=tf.subtract(train_out,output)
mse=tf.reduce_mean(tf.square(error))

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(output))
print(sess.run(error))
print(sess.run(mse))


[[ 1.]
 [ 1.]
 [-1.]
 [-1.]]
[[0.]
 [0.]
 [2.]
 [0.]]
1.0
